# Generated by Django 4.2.13 on 2026-05-03 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niche_input', models.TextField(verbose_name='Nicho / Idea')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Título del Proyecto')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('niche_done', 'Nicho Analizado'), ('offer_done', 'Oferta Creada'), ('outline_done', 'Índice Creado'), ('copy_done', 'Copies Generados'), ('complete', 'Completo')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductOutline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('ebook', 'E-book'), ('course', 'Curso'), ('workbook', 'Workbook'), ('guide', 'Guía Rápida')], default='ebook', max_length=20)),
                ('title', models.CharField(blank=True, max_length=250)),
                ('subtitle', models.CharField(blank=True, max_length=350)),
                ('description', models.TextField(blank=True)),
                ('chapters', models.JSONField(default=list)),
                ('raw_response', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_outline', to='core.project')),
            ],
            options={
                'verbose_name': 'Índice del Producto',
            },
        ),
        migrations.CreateModel(
            name='OfferStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=200)),
                ('tagline', models.CharField(blank=True, max_length=350)),
                ('price_points', models.JSONField(default=list)),
                ('bonuses', models.JSONField(default=list)),
                ('guarantee', models.TextField(blank=True)),
                ('value_stack', models.JSONField(default=list)),
                ('total_value', models.CharField(blank=True, max_length=50)),
                ('your_investment', models.CharField(blank=True, max_length=50)),
                ('upsell', models.JSONField(default=dict)),
                ('order_bump', models.JSONField(default=dict)),
                ('raw_response', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offer_structure', to='core.project')),
            ],
            options={
                'verbose_name': 'Estructura de Oferta',
            },
        ),
        migrations.CreateModel(
            name='NicheAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_name', models.CharField(blank=True, max_length=150)),
                ('buyer_personas', models.JSONField(default=list)),
                ('pains', models.JSONField(default=list)),
                ('desires', models.JSONField(default=list)),
                ('fears', models.JSONField(default=list)),
                ('barriers', models.JSONField(default=list)),
                ('product_names', models.JSONField(default=list)),
                ('epiphany_bridge', models.TextField(blank=True)),
                ('raw_response', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='niche_analysis', to='core.project')),
            ],
            options={
                'verbose_name': 'Análisis de Nicho',
            },
        ),
        migrations.CreateModel(
            name='CopyLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headlines', models.JSONField(default=list)),
                ('hooks', models.JSONField(default=list)),
                ('short_description', models.TextField(blank=True)),
                ('pas_copy', models.TextField(blank=True)),
                ('aida_copy', models.TextField(blank=True)),
                ('cta_options', models.JSONField(default=list)),
                ('raw_response', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='copy_library', to='core.project')),
            ],
            options={
                'verbose_name': 'Biblioteca de Copies',
            },
        ),
    ]
