# Generated by Django 4.2.11 on 2026-05-03 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ai_model',
            field=models.CharField(choices=[('gpt-4o', 'GPT-4o — Estructura y JSON'), ('claude-3-5-sonnet-20241022', 'Claude 3.5 Sonnet — Redacción Creativa')], default='gpt-4o', max_length=50, verbose_name='Modelo de IA'),
        ),
        migrations.AddField(
            model_name='project',
            name='brand_voice',
            field=models.CharField(choices=[('mentor', '🎓 Mentor Sabio y Empático'), ('friend', '😎 Amigo Sarcástico y Directo'), ('scientist', '🔬 Científico Riguroso y Preciso'), ('coach', '💪 Coach Motivacional Intenso'), ('expert', '🏆 Experto Autoritario y Serio')], default='mentor', max_length=20, verbose_name='Voz de Marca'),
        ),
        migrations.CreateModel(
            name='ChapterContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_number', models.PositiveSmallIntegerField()),
                ('title', models.CharField(blank=True, max_length=250)),
                ('content', models.TextField(blank=True)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('done', 'Completado')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_contents', to='core.project')),
            ],
            options={
                'verbose_name': 'Contenido de Capítulo',
                'ordering': ['chapter_number'],
                'unique_together': {('project', 'chapter_number')},
            },
        ),
    ]
