# Generated by Django 4.2.11 on 2026-05-03 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_project_ai_model_project_brand_voice_chaptercontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('pdf', 'Archivo PDF'), ('url', 'Página Web')], max_length=5)),
                ('title', models.CharField(blank=True, max_length=300, verbose_name='Título / descripción')),
                ('url', models.URLField(blank=True, max_length=2000, verbose_name='URL de la página')),
                ('pdf_file', models.FileField(blank=True, upload_to='user_resources/', verbose_name='Archivo PDF')),
                ('extracted_text', models.TextField(blank=True, verbose_name='Texto extraído')),
                ('char_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_resources', to='core.project')),
            ],
            options={
                'verbose_name': 'Recurso del Usuario',
                'ordering': ['-created_at'],
            },
        ),
    ]
