# Generated by Django 4.2.11 on 2026-05-03 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userresource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('niche_done', 'Nicho Analizado'), ('offer_done', 'Oferta Creada'), ('revenue_done', 'Revenue Diseñado'), ('outline_done', 'Índice Creado'), ('copy_done', 'Copies Generados'), ('complete', 'Completo')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='RevenueStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_bump', models.JSONField(default=dict)),
                ('upsell', models.JSONField(default=dict)),
                ('raw_response', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_strategy', to='core.project')),
            ],
            options={
                'verbose_name': 'Estrategia de Revenue',
            },
        ),
    ]
