# Generated by Django 4.2.11 on 2026-05-03 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_project_status_revenuestrategy'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifact_type', models.CharField(choices=[('angles', 'Generador de Ángulos'), ('visual_identity', 'Identidad Visual'), ('mockups', 'Mockups Premium'), ('ads_generator', 'Generador de Ads'), ('landing_page', 'Landing Page'), ('product_copies', 'Copys de Producto'), ('ad_copies', 'Copys para Ads'), ('premium_scripts', 'Guiones Premium'), ('ugc_realistic', 'UGC Realistas'), ('email_marketing', 'Email Marketing'), ('global_export', 'Exportar y Vender Global')], max_length=40)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('payload', models.JSONField(default=dict)),
                ('raw_response', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('done', 'Completado'), ('error', 'Error')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='core.project')),
            ],
            options={
                'verbose_name': 'Artefacto del Proyecto',
                'ordering': ['artifact_type'],
                'unique_together': {('project', 'artifact_type')},
            },
        ),
    ]
