# Generated by Django 4.2.11 on 2026-05-03 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_projectartifact'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='max_simultaneous_tests',
            field=models.PositiveSmallIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='project',
            name='plan_tier',
            field=models.CharField(default='plan_a_29', max_length=30),
        ),
        migrations.AddField(
            model_name='project',
            name='primary_market',
            field=models.CharField(choices=[('AR', 'Argentina'), ('MX', 'México'), ('CO', 'Colombia'), ('CL', 'Chile'), ('UY', 'Uruguay'), ('BR', 'Brasil'), ('ES', 'España'), ('OTRO', 'Otro mercado')], default='AR', max_length=10, verbose_name='Mercado principal'),
        ),
        migrations.AddField(
            model_name='project',
            name='target_markets',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='projectartifact',
            name='artifact_type',
            field=models.CharField(choices=[('angles', 'Generador de Ángulos'), ('visual_identity', 'Identidad Visual'), ('mockups', 'Mockups Premium'), ('ads_generator', 'Generador de Ads'), ('nano_banana_ads', 'Imágenes Ads NANO BANANA 3 PRO'), ('offer_visual_model', 'Modelado de Oferta Visual'), ('landing_page', 'Landing Page'), ('product_copies', 'Copys de Producto'), ('ad_copies', 'Copys para Ads'), ('product_bonus_pack', 'Generador de Producto + Bonus'), ('premium_scripts', 'Guiones Premium'), ('ugc_realistic', 'UGC Realistas'), ('email_marketing', 'Email Marketing'), ('global_export', 'Exportar y Vender Global')], max_length=40),
        ),
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'En ejecución'), ('completed', 'Completado'), ('failed', 'Fallido')], default='running', max_length=15)),
                ('requested_features', models.JSONField(blank=True, default=list)),
                ('generated_count', models.PositiveSmallIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_runs', to='core.project')),
            ],
            options={
                'verbose_name': 'Ejecución de Testeo',
                'ordering': ['-started_at'],
            },
        ),
    ]
