# Generated by Django 4.2.11 on 2026-05-03 22:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_project_max_simultaneous_tests_project_plan_tier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanAEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('active', 'Activo'), ('cancelled', 'Cancelado')], default='pending', max_length=15)),
                ('purchased_at', models.DateTimeField(blank=True, null=True)),
                ('credentials_email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('first_login_at', models.DateTimeField(blank=True, null=True)),
                ('first_project_launched_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan_a_enrollment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plan A Enrollment',
            },
        ),
    ]
