# Generated by Django 4.2.11 on 2026-05-03 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_planaenrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='planaenrollment',
            name='cancel_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='planaenrollment',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planaenrollment',
            name='upgraded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planaenrollment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('active', 'Activo'), ('cancelled', 'Cancelado'), ('upgraded', 'Actualizado a Plan B')], default='pending', max_length=15),
        ),
        migrations.CreateModel(
            name='PlanBEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('cancelled', 'Cancelado')], default='active', max_length=15)),
                ('upgraded_from_plan_a', models.BooleanField(default=False)),
                ('purchased_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan_b_enrollment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plan B Enrollment',
            },
        ),
    ]
