# Generated by Django 4.2.11 on 2026-05-03 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_plan_b_enrollment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvatarProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatars', models.JSONField(default=list)),
                ('buyer_persona_summary', models.TextField(blank=True)),
                ('raw_response', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avatar_profile', to='core.project')),
            ],
            options={
                'verbose_name': 'Avatares y Buyer Persona',
            },
        ),
    ]
