# Generated by Django 4.2.13 on 2026-05-04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_avatar_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterRewriteHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_number', models.PositiveSmallIntegerField()),
                ('previous_content', models.TextField()),
                ('previous_word_count', models.PositiveIntegerField(default=0)),
                ('tone', models.CharField(blank=True, max_length=120)),
                ('scope', models.CharField(default='full', max_length=10)),
                ('shorten_percent', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('undone_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_rewrite_history', to='core.project')),
            ],
            options={
                'verbose_name': 'Historial de Reescritura de Capítulo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='chapterrewritehistory',
            index=models.Index(fields=['project', 'chapter_number', 'undone_at'], name='core_chapte_project_3ee2bd_idx'),
        ),
    ]
