# Generated by Django 4.2.13 on 2026-05-04 13:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0010_chapterrewritehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookChapter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chapter_number', models.IntegerField()),
                ('title', models.TextField(blank=True)),
                ('body_text', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('done', 'Completado')], default='draft', max_length=20)),
            ],
            options={
                'verbose_name': 'Book Chapter',
                'db_table': 'book_chapters',
                'ordering': ['chapter_number'],
            },
        ),
        migrations.CreateModel(
            name='ProjectStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(16)])),
                ('step_name', models.TextField()),
                ('content', models.JSONField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project Step',
                'db_table': 'project_steps',
                'ordering': ['step_number'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('niche', models.TextField(blank=True)),
                ('target_country', models.TextField(blank=True)),
                ('target_audience', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('completed', 'Completado'), ('active', 'Activo')], default='draft', max_length=20)),
                ('progress_percentage', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Workflow Project',
                'db_table': 'projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='chapterrewritehistory',
            new_name='core_chapte_project_ed7ece_idx',
            old_name='core_chapte_project_3ee2bd_idx',
        ),
        migrations.AddField(
            model_name='workflowproject',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectstep',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='core.workflowproject'),
        ),
        migrations.AddField(
            model_name='bookchapter',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_chapters', to='core.workflowproject'),
        ),
        migrations.AddConstraint(
            model_name='projectstep',
            constraint=models.UniqueConstraint(fields=('project', 'step_number'), name='uniq_project_step_number'),
        ),
    ]
