# Generated by Django 4.2.13 on 2026-05-04 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_bookchapter_projectstep_workflowproject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowproject',
            name='source_project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_snapshot', to='core.project'),
        ),
        migrations.AddConstraint(
            model_name='bookchapter',
            constraint=models.UniqueConstraint(fields=('project', 'chapter_number'), name='uniq_book_chapter_number'),
        ),
    ]
