# Generated by Django 4.2.13 on 2026-05-04 14:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_workflowproject_source_project_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chapter_number', models.IntegerField()),
                ('chapter_title', models.TextField()),
                ('content', models.TextField(blank=True)),
                ('word_count', models.IntegerField(default=0)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_contents', to='core.project')),
            ],
            options={
                'verbose_name': 'Book Content',
                'db_table': 'book_content',
                'ordering': ['chapter_number'],
            },
        ),
        migrations.AddConstraint(
            model_name='bookcontent',
            constraint=models.UniqueConstraint(fields=('project', 'chapter_number'), name='uniq_book_content_chapter'),
        ),
    ]
