"""Django admin registrations for the main MagicBook domain models."""

from django.contrib import admin
from .models import Project, NicheAnalysis, OfferStructure, ProductOutline, CopyLibrary


# Project dashboard in admin: status, owner and quick search.
@admin.register(Project)
class ProjectAdmin(admin.ModelAdmin):
    list_display = ['id', 'title', 'user', 'status', 'created_at']
    list_filter = ['status', 'created_at']
    search_fields = ['title', 'niche_input', 'user__username']
    readonly_fields = ['created_at', 'updated_at']


# Niche analysis read model for quick inspection in backoffice.
@admin.register(NicheAnalysis)
class NicheAnalysisAdmin(admin.ModelAdmin):
    list_display = ['project', 'avatar_name', 'created_at']
    raw_id_fields = ['project']


# Offer structure with pricing-related fields.
@admin.register(OfferStructure)
class OfferStructureAdmin(admin.ModelAdmin):
    list_display = ['project', 'product_name', 'your_investment', 'created_at']
    raw_id_fields = ['project']


# Product outline and chapter structure.
@admin.register(ProductOutline)
class ProductOutlineAdmin(admin.ModelAdmin):
    list_display = ['project', 'title', 'product_type', 'created_at']
    raw_id_fields = ['project']


# Copy library generated by AI per project.
@admin.register(CopyLibrary)
class CopyLibraryAdmin(admin.ModelAdmin):
    list_display = ['project', 'created_at']
    raw_id_fields = ['project']
